services:
  - type: web
    name: breast-cancer-api
    runtime: python-3.11.9
    plan: free
    autoDeploy: false
    buildCommand: |
      pip install --upgrade pip
      pip install wheel setuptools
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    

